apiVersion: v2
name: meshplay
description: Meshplay chart for deploying Meshplay and Meshplay's adapters.
icon: https://meshplay.io/images/logos/meshplay-logo.png
kubeVersion:
keywords:
  - meshplay
  - meshplay-istio
  - meshplay-linkerd
  - meshplay-consul
  - meshplay-kuma
  - meshplay-nsm
  - meshplay-traefik-mesh
  - meshplay-nginx-sm
  - meshplay-app-mesh
  - meshplay-nighthawk
source:
  - https://github.com/khulnasoft/meshplay

engine: gotpl

deprecated: false

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
version: 0.7.0

# This is the version number of the application being deployed. This version number should be incremented each time you make changes to the application.
# appVersion: v0.6.0

dependencies:
  - name: meshplay-istio
    version: 0.7.0
    condition: meshplay-istio.enabled
  - name: meshplay-linkerd
    version: 0.7.0
    condition: meshplay-linkerd.enabled
  - name: meshplay-consul
    version: 0.7.0
    condition: meshplay-consul.enabled
  - name: meshplay-kuma
    version: 0.7.0
    condition: meshplay-kuma.enabled
  - name: meshplay-nsm
    version: 0.7.0
    condition: meshplay-nsm.enabled
  - name: meshplay-traefik-mesh
    version: 0.7.0
    condition: meshplay-traefik-mesh.enabled
  - name: meshplay-nginx-sm
    version: 0.7.0
    condition: meshplay-nginx-sm.enabled
  - name: meshplay-app-mesh
    version: 0.7.0
    condition: meshplay-app-mesh.enabled
  - name: meshplay-cilium
    version: 0.7.0
    condition: meshplay-cilium.enabled
  - name: meshplay-nighthawk
    version: 0.7.0
    condition: meshplay-nighthawk.enabled

maintainers:
  - name: Meshplay Authors
    email: maintainers@meshplay.io

