apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose.yaml
    kompose.version: 1.32.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: meshplay-istio
  name: meshplay-istio
spec:
  selector:
    matchLabels:
      io.kompose.service: meshplay-istio
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: meshplay-istio
    spec:
      serviceAccount: meshplay-server
      containers:
      - image: layer5/meshplay-istio:stable-latest
        imagePullPolicy: Always
        name: meshplay-istio
        ports:
        - containerPort: 10000
        resources: {}
      restartPolicy: Always
status: {}
