name: Discussion data files update

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' #runs every day at midnight

jobs:
  update:
    runs-on: ubuntu-latest
    if: github.repository == 'meshplay/meshplay'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_ACCESS_TOKEN }}
      - name: Fetch data for meshplayctl tag
        run: curl https://discuss.layer5.io/tag/meshplayctl.json -o docs/_data/discuss/meshplayctl.json
      - name: Fetch data for meshplay tag
        run: curl https://discuss.layer5.io/tag/meshplay.json -o docs/_data/discuss/meshplay.json

      - name: Pull changes from remote
        run: git pull origin master

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          file_pattern: docs/_data/discuss/*.json
          commit_user_name: Discussions bot
          commit_user_email: discussions@meshplay.khulnasoft.com
          commit_author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          commit_options: "--signoff"
          commit_message: "latest discussion data files added"
          branch: master